### ISSUE TITLE
请问是否支持less

### ISSUE THREAD

**Issue by SMIELPF** [gaoxiaoliangz/react-scoped-css#13]
在开发中用less比较多，想知道这个是否支持less

**Comment by suiyuex** [comment]
maybe help you https://github.com/suiyuex/react-scoped-css

**Comment by gaoxiaoliangz** [comment]
@SMIELPF 在 webpack 配置里 scoped-css-loader 后面加上 less-loader, 给 babel-plugin-react-scoped-css 加个 include 配置

```
"plugins": [
  [
    "babel-plugin-react-scoped-css",
    {
      "include": ".scoped.less$"
    }
  ]
]
```
这样理论上是可行的，有时间我会把这个加到 example 里面

**Comment by villaincoder** [comment]
@SMIELPF 正好有类似的需要 写了个扩展https://github.com/villaincoder/craco-scoped-less
