### ISSUE TITLE
Works with Semantic UI?

### ISSUE THREAD

**Issue by Gomez** [gaoxiaoliangz/react-scoped-css#20]
I tried to scope Semantic UI like this:

import "./semantic.min.scoped.css";

The css is from this bundle: https://www.npmjs.com/package/semantic-ui-css

It worked for some classes but not all. Should this work?

**Comment by Gomez** [comment]
I found a workaround by only using the needed components, like:

import "semantic-ui-css/components/button.min.css"

Better but not perfect.

**Comment by gaoxiaoliangz** [comment]
react-scoped-css is trying to scope css in component level. Say you have A.jsx and A.scoped.css, A.scoped.css is scoped to A.jsx. It is not recommended to import a css lib as scoped, since it will be scoped only to the component which imported it.
