### ISSUE TITLE
[BUG] not support scss interpolation

### ISSUE THREAD

**Issue by chenxxzhe** [gaoxiaoliangz/react-scoped-css#21]
use interpolation in scss will error: 

```
Syntax Error: SyntaxError

(12:11) Unknown word

  10 |   @each $side in $sides {
  11 |     @if $side == 'all' {
> 12 |       .m#{str-slice($side, 0, 1)}-#{$space} {
     |           ^
  13 |         margin: gen_spacing($space);
  14 |       }
```

**Comment by gaoxiaoliangz** [comment]
This is unlikely to be a bug in react-scoped-css, since all pre-processers will be executed before scoped-css-loader. That is to say soped-css-loader will always process raw css source. If not, your webpack config may be configured wrong. Can you provider the config you are using?
