### ISSUE TITLE
it can't work with antd UI lib

### ISSUE THREAD

**Issue by hanmingpan** [gaoxiaoliangz/react-scoped-css#22]
ordinary element can be work.
but UI element's props Classname can't be work.

**Comment by gaoxiaoliangz** [comment]
The data-v-hash prop should be passed down to make it work.

For example:

```jsx
const Button = ({children, ...rest}) => {
  return <button {...rest}>{children}</button>
}

```

**Comment by hanmingpan** [comment]
> The data-v-hash prop should be passed down to make it work. As it is passed by babel at compile time, you have to do it this way:
> 
> ```js-jsx
> const Button = ({children, ...rest}) => {
>   return <button {...rest}>{children}</button>
> }
> ```

thank you!!!
