### ISSUE TITLE
Include component name of path in hash?

### ISSUE THREAD

**Issue by stefaneidelloth** [gaoxiaoliangz/react-scoped-css#29]
Lets say, I have css class 'foo' for components Baa and Qux... and I debug the final application with chrome dev tools...
how to I know where the css class foo[hash] comes from?

=>How can I include the name of the component in the hash to get

foo[Baa-hash] vs. foo[Qux-hash]

If I have two components with the same name in different packages, It would be good to include the full path:

foo[package_a/Baa-hash] vs. foo[package_b/Baa-hash]

**Comment by gaoxiaoliangz** [comment]
It seems to be a good idea. Despite the fact that usually each component should have its own css file, I think I might implement something to let users customize the hash generating function.

**Comment by stefaneidelloth** [comment]
I just had a look at the dev tools. If the source map would work correctly, that would also be fine for me.

![image](https://user-images.githubusercontent.com/12675339/86357506-3338b400-bc6e-11ea-8d18-0bd3ea12bbb8.png)

However, If I Tools.scoped.css exists twice (in different folders), the link Tools.scoped.css:1 seems to point to the same file for both hashes:
.tools[data-v-c1c98b61]
and 
.tools[data-v-db194bb4]

**Comment by gaoxiaoliangz** [comment]
Checkout `examples/simple/src` in this repo, specificly `TextA` and `TextB`. They both have a css file named `Text.scoped.scss`, and the soucemap is correct.
Maybe something else is mis configured? Or if you can provide a mini-repo to reproduce the problem, I may look into it more closely.
