### ISSUE TITLE
Using `ts-loader` will not call `JSXElement`

### ISSUE THREAD

**Issue by ryanypm** [gaoxiaoliangz/react-scoped-css#4]
How can I get the `tsx` file to work?

**Comment by gaoxiaoliangz** [comment]
Can you provide more detailes with some code blocks or even better a mini repo?

**Comment by ryanypm** [comment]
> Can you provide more detailes with some code blocks or even better a mini repo?

Thanks for the reply.
Here is a simple demo.
https://github.com/ryanypm/webpack-scoped-demo

**Comment by gaoxiaoliangz** [comment]
In `tsconfig.json`, change `jsx` in `compilerOptions` to `preserve` and it will work.

**Comment by ryanypm** [comment]
> In `tsconfig.json`, change `jsx` in `compilerOptions` to `preserve` and it will work.

thank you very much.
