### ISSUE TITLE
Cannot install with npm

### ISSUE THREAD

**Issue by christianvari** [gaoxiaoliangz/react-scoped-css#42]
Hi, I got this error installing it with npm 7.11.2 and nodejs 12.16.1

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: @craco/craco@6.1.0
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"6.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @craco/craco@"^5.3.0" from craco-plugin-scoped-css@1.1.0
npm ERR! node_modules/craco-plugin-scoped-css
npm ERR!   craco-plugin-scoped-css@"1.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by gaoxiaoliangz** [comment]
I cannot reproduce this error. Is it something to do with your npm registry config? Or try to install `@craco/craco@5.3.0` manually.

**Comment by yaqwsx** [comment]
Well, the problem appears as there is a version conflict - you require `craco@"^5.3.0"`, but @christianvari has `craco@6.1.0`. Is there a reason you support only version 5 of craco?

**Comment by christianvari** [comment]
Yes as @yaqwsx has pointed out, I'm using craco 6.1.0. Seems that only version 5 is supported. Can we extend this also to craco 6?

**Comment by Aldo111** [comment]
HI any update on this?

**Comment by piyushk96** [comment]
@gaoxiaoliangz Can you please update the package on npm also

**Comment by raul-perez-m** [comment]
@gaoxiaoliangz Hi! Still having issues with the npm version, as it hasn't been updated yet.
