### ISSUE TITLE
Can I use at babel v6?

### ISSUE THREAD

**Issue by moonjoungyoung** [gaoxiaoliangz/react-scoped-css#43]
Hello.

I am using babel 6.26.0 ;
Can I use at babel v6?

**Comment by gaoxiaoliangz** [comment]
By the time of the development, babel 7 is already used. I have not tested it with babel 6.x.
Maybe it's time to do a little upgrade?

**Comment by moonjoungyoung** [comment]
@gaoxiaoliangz 

I want to upgrade, but it is the project from my company.. I can't upgrade it for myself.
