### ISSUE TITLE
Compatible with Webpack 5

### ISSUE THREAD

**Issue by AntonZelenkov1997** [gaoxiaoliangz/react-scoped-css#44]
Hello. I have a question. Do you have support with Webpack 5? I had difficulty with this. The data attribute is not generated for html tags. I downloaded the example

https://github.com/gaoxiaoliangz/react-scoped-css/tree/master/examples/simple

This example works great. I updated the dependencies, removed the errors and configured it to work on webpack 5, but the date attribute is still not generated.

P.S. I really like your approach to css-modules.

**Comment by d-lach** [comment]
got a similar issue, I am using typescript and dunno why babel plugin fails to add the attribute. Has is added properly in the scss though.

**Comment by someonewithpc** [comment]
See https://github.com/gaoxiaoliangz/react-scoped-css/pull/74
