### ISSUE TITLE
cloneElement support

### ISSUE THREAD

**Issue by LoganDark** [gaoxiaoliangz/react-scoped-css#45]
Doesn't look like this supports React.cloneElement

**Comment by gaoxiaoliangz** [comment]
No it doesn't. Because the data-v-hash is added on jsx elements only.

**Comment by LoganDark** [comment]
> No it doesn't. Because the data-v-hash is added on jsx elements only.

Yeah, I can work around this by specifying `...(<div />).props`. It works quite well
