### ISSUE TITLE
targeting untagged elements

### ISSUE THREAD

**Issue by LoganDark** [gaoxiaoliangz/react-scoped-css#47]
I have a `prose` class from tailwindcss that styles all `p` and `a` and `h1` and etc. elements inside of it, but the problem is those `p` and `a` and `h1` elements do not have the data-v-whatever tag that react-scoped-css adds. So I need to find a way to target those, but it appears this isn't supported. :/

**Comment by LoganDark** [comment]
Oh, if I append `/deep/` to the selector then `prose` works perfectly. Had to switch to node-sass, but I'm already using craco so it's no big deal. Yay

**Comment by LoganDark** [comment]
Nevermind, `node-sass` does not support `:not`, and `sass` has said it will never ever support `/deep/` or `>>>`

**Comment by LoganDark** [comment]
I think I worked around this at the time by having a separate completely unscoped CSS file just for this. I'm assuming the closure is because there's some other solution to this now? Is it #60?

**Comment by gaoxiaoliangz** [comment]
@LoganDark Yes, I believe #60 can solve your problem.

**Comment by LoganDark** [comment]
If it works, then it should. I don't have that problem anymore, I've long since left that project. But hopefully in the future it should be a solved problem.
