### ISSUE TITLE
The effect is not applied with an import within the scoped.scss file

### ISSUE THREAD

**Issue by Anddr3s** [gaoxiaoliangz/react-scoped-css#51]
I downloaded the example, and imported bootstrap inside a scoped file, but the styles also affected all other components.

**Comment by Anddr3s** [comment]
To solve this problem, I downloaded the bootstrap library for React, since it was not compatible with the CDN.

**Comment by TuYouYiDuiDaZhuTiZi** [comment]
I have encountered the same problem, how did you solve it?

**Comment by Anddr3s** [comment]
For resolve my problem, I used the sass scoped mode.
