### ISSUE TITLE
/deep/ selector issues with dart-sass

### ISSUE THREAD

**Issue by sanghogu** [gaoxiaoliangz/react-scoped-css#66]
"react": "^18.2.0",
    "react-bootstrap": "^2.5.0",
    "react-datepicker": "^4.8.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^11.18.5",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "craco-plugin-scoped-css": "^1.1.1",

node version : 16.13

Using the above dependency, the /deep/ selector cannot be used. Can you specify an alternative selector?

**Comment by someonewithpc** [comment]
I believe you should use `:deep`, as in `/deep/ :local(.grid)` becomes `:deep(:local(.grid))`

**Comment by gaoxiaoliangz** [comment]
#60
