### ISSUE TITLE
Problem with Test with jest

### ISSUE THREAD

**Issue by vinimarcili** [gaoxiaoliangz/react-scoped-css#67]
I have a problem trying to test a component that imports another component with .scoped.scss.
Something along these lines:

```
- components
   - some-component.tsx
- pages
   - some-page.tsx // this imports the some-component
```

When I run a test I get the error:
```Cannot find module: some-component.scoped.scss?scopeId=xxxxx```

I already configured jest.config with moduleNameMapper '\\.(css|scss|sass)$': 'identity-obj-proxy',

**Comment by diamondskrt** [comment]
add this to moduleNameMapper in jest.config:
`'\\.scoped.(css|scss)': 'identity-obj-proxy',`
