### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by shubh710** [gaoxiaoliangz/react-scoped-css#8]
do I need to install any npm module before craco if I am using CRA?
seems like scoped-css-loader needs to be installed but not in the document.

**Comment by gaoxiaoliangz** [comment]
You can refer to [Use in an existing create-react-app project (which hasn't been ejected yet)](https://github.com/gaoxiaoliangz/react-scoped-css#use-in-an-existing-create-react-app-project-which-hasnt-been-ejected-yet) in the docs.

In short you have to install `craco-plugin-scoped-css` and `@craco/craco`, if you are using CRA.

You can also refer to the [cra example](https://github.com/gaoxiaoliangz/react-scoped-css/tree/master/examples/cra).
